name: Unzip and Commit Panel

on:
  workflow_dispatch:

permissions:
  contents: write   # yeh line zaroori hai push ke liye

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip panel
        run: |
          rm -rf coramtix-panel
          unzip coramtix-panel-full.zip -d coramtix-panel

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped panel source code" || echo "No changes"
          git push origin HEAD:main
