name: Unzip and Commit Panel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip panel (direct into repo root)
        run: |
          unzip -o coramtix-panel-full.zip
          rm -f coramtix-panel-full.zip   # optional: zip delete

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped panel source code" || echo "No changes"
          git push origin HEAD:main
